[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "osnap"
dist-name = "o-snap"
author = "osnap developers"
author-email = "ek@knaaptime.com"
home-page = "http://spatialucr.edu"
requires-python = ">=3.5"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
]
